## PRO TIP : Test your changes locally with :
## gitlab-ci-multi-runner exec docker {name_of_the_job}

##
## V A R I A B L E S
##

variables:
  # $ARTIFACTS is required by artefacts_private_env.yml
  ARTIFACTS: '*'
  # $THEME_BRANCH is required by build_pandocker_stable.yml
  THEMES_BRANCH: 'stable'

##
## I N C L U D E S
##

include:
  # B U I L D
  # Launch `make all` with the pandocker machine
  - project: 'dalibo/gitlab-templates'
    file: 'build_pandocker_stable.yml'

  # D E P L O Y
  # Export artefacts to the private environment
  - project: 'dalibo/gitlab-templates'
    file: 'artifacts/base.yml'


deploy:private_env:
  extends: .artifacts:deploy_private_env

# This clean up job is mandatory if you extend .artifacts:deploy_private_env
deploy:clean_up_private_env:
  extends: .artifacts:clean_up_private_env
